name: Initialize

on:
  workflow_dispatch:
    inputs:
      company-name:
        description: "Company Name"
        required: true
      package-name:
        description: "Package Name"
        required: true

permissions:
  contents: write

jobs:
  call-local-rename-workflow:
    uses: ./.github/workflows/rename-package.yml
    with:
      company-name: ${{ inputs.company-name }}
      package-name: ${{ inputs.package-name }}
  
  initialize:
    runs-on: ubuntu-latest
    needs: [call-local-rename-workflow]

    steps:
      - run: |
          echo "default-symlink-setting=$(git config --global --get core.symlink)" >> $GITHUB_OUTPUT
          git config --global core.symlinks false
        id: symlink-setting

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - name: Remove and Clear Files
        run: |
          echo "Initializing README.md"
          echo "# ${{ inputs.package-name }}" > Documentation~/index.md
          
          echo "Clearing documentation"
          rm -f Documentation~/manual/*
          rm -f Documentation~/resources/*
          
          echo "Removing '.meta' files"
          find . -name '*.meta' -type f -delete
          
          echo "Updating documentation url in package.json"
          REPO_NAME=$(echo "${{ github.repository }}" | cut -d '/' -f 2 | tr '[:upper:]' '[:lower:]')
          REPO_OWNER=$(echo "${{ github.repository }}" | cut -d '/' -f 1 | tr '[:upper:]' '[:lower:]')
          jq ".documentationUrl = \"$REPO_OWNER.github.io/$REPO_NAME\"" package.json > temp.json && mv temp.json package.json
          
          echo "Removing initialization workflow file"
          rm .github/workflows/initialize.yml
          
      - run: git config --global core.symlink "${{ steps.symlink-setting.output.default-symlink-setting }}"

      - name: Commit and Push
        uses: EndBug/add-and-commit@v9.1.1
        with:
          message: Initialized Package
          committer_name: GitHub Actions
          committer_email: 41898282+github-actions[bot]@users.noreply.github.com
